In [2]:
import numpy
import math

In [3]:
grid = numpy.zeros((4, 4), dtype=int)
print(grid.flatten())


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [4]:
def move(flattenedGrid, key):
    # temp = grid
    size = int(math.sqrt(len(flattenedGrid)))
    print(size)

    grid = numpy.zeros((size, size), dtype=int)

    for i in range(size):
        grid[i][:] = flattenedGrid[i*size : size*(i + 1)]

    for i in range(size):
        flipped = False
        if key in 'lr':  
            row = grid[i, :]
        else:
            row = grid[:, i] 

        if key in 'rd':  
            flipped = True
            row = row[::-1]

        notZeros = _get_num(row) 
        newRow = numpy.zeros_like(row)
        newRow[:len(notZeros)] = notZeros  

        if flipped:
            newRow = newRow[::-1]

        if key in 'lr':
            grid[i, :] = newRow
        else:
            grid[:, i] = newRow

    return grid.flatten()

def _get_num(row):
    notZeros = row[row != 0]
    res = []
    skip = False
    for i in range(len(notZeros)):
        if skip:
            skip = False
            continue
        if i != len(notZeros) - 1 and notZeros[i] == notZeros[i + 1]: 
            sum = notZeros[i] * 2
            res.append(sum)
            skip = True
        else:
            res.append(notZeros[i])
    return res

In [5]:
test = numpy.full((4,4), 2)

test3 = [1,1,1,1]

test[0][:] = test3[0:4]
print(test)

[[1 1 1 1]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [12]:
grid = numpy.array([
    [2,0,4,0],
    [2,0,4,5],
    [2,0,4,5],
    [2,0,4,5]
    ])

grid2 = numpy.array([2,0,9,8,10,0])

# unoccupied_pos = list(zip(*numpy.where(grid2 == 0)))
unoccupied_pos = list(*numpy.where(grid2 == 0))


print(unoccupied_pos)
print(*grid2)
print(list(*numpy.where(grid2 == 0)))
# for i in unoccupied_pos:
# print(grid[(0,1)])

[1, 5]
2 0 9 8 10 0
[1, 5]


In [ ]:
maxValPos = list(*numpy.where(grid2 == max(grid2)))

print(maxValPos)

if 3 in maxValPos or 4 in maxValPos:
    print( "yes")
else:
        print("no")

[4]
yes


In [ ]:
import numpy

childList = numpy.array([
                        [4,5,7,3,0,8,7,0],
                        [4,5,7,3,0,9,7,0],
                        [4,5,7,3,0,8,7,0]
                        ])

# for i in enumerate(childList):
print(childList[1,:])


[4 5 7 3 0 9 7 0]


In [ ]:
arr = numpy.array([1,2,0,2,3,4,0,5])

print(arr[arr!=0])

[1 2 2 3 4 5]
